export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  READ = 'READ',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE',
  UPDATE_STATUS = 'UPDATE_STATUS',
} 